#!/bin/bash

INSTALL_DIR=$(pwd)/../installdir
USER_SOURCE=circuits/qft.c
OUTPUT_EXE=qft
DISTRIBUTED=1
MULTITHREADED=1
GPUACCELERATED=0

CC=icc
CXX=icpc

cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
  -DCMAKE_C_COMPILER=${CC} \
  -DCMAKE_CXX_COMPILER=${CXX} \
  -DUSER_SOURCE=${USER_SOURCE} \
  -DOUTPUT_EXE=${OUTPUT_EXE} \
  -DDISTRIBUTED=${DISTRIBUTED} \
  -DMULTITHREADED=${MULTITHREADED} \
  -DGPUACCELERATED=${GPUACCELERATED} \
  ..
